services:
  postgres:
    image: postgres:15
    container_name: lab2_postgres
    environment:
      POSTGRES_DB: lab2
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/csv_data
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spark-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d lab2"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-master:
    image: apache/spark:3.5.0
    container_name: lab2_spark_master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark-jobs:/spark-jobs
    networks:
      - spark-net

  spark-worker:
    image: apache/spark:3.5.0
    container_name: lab2_spark_worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
    volumes:
      - ./spark-jobs:/spark-jobs
    networks:
      - spark-net

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: lab2_clickhouse
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-config:/etc/clickhouse-server/users.d
    networks:
      - spark-net
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  postgres_data:
  clickhouse_data:

networks:
  spark-net:
    driver: bridge
